=== ButakovaLudmila/ITMO/XML/Lab3/library_XML.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="library">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book_catalog">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="book">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="authors">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="author" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="title" type="xs:string" />
                    <xs:element name="publishing" type="xs:string" />
                    <xs:element name="annotation" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string"" />
                  <xs:attribute name="isbn" type="xs:string"" />
                  <xs:attribute name="year" type="xs:date" />
                  <xs:attribute name="issue" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="author_catalog">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="author_book">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="idref" type="xs:string"" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ButakovaLudmila/ITMO/XML/Lab3/library.xml
<?xml version="1.0"?>
<library xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/butakovalv/Documents/GitRepo/ITMO/XML/Lab3/library_XML.xsd">

  <!-- библиотека -->
    <!-- каталог книг -->
    <book_catalog>
	
       <book id="N1"  isbn="978-5-4461-1937-0" year="2022" issue="translation">
	   <authors>
        <author>Шредер К.</author>		
        </authors>
        <title>Linux. Книга рецептов</title>
        <publishing>Питер</publishing>
        <annotation>Книга рецептов обучит начинающих пользователей и администраторов Linux управлять системой, используя как графические инструменты, так и командную строку. Независимо от того, используете ли вы Linux во встроенных или настольных системах, серверах, облачных или виртуальных средах, фундаментальные приемы одни. Цель книги - помочь вам быстро приступить к работе на простых и наглядных примерах. Карла Шредер приводит рецепты с объяснениями для конкретных ситуаций, а также ссылки для дополнительного изучения.</annotation>
	   </book>   
       
	   
    </book_catalog>
	
    <!-- каталог авторов -->
    <author_catalog>
       <author_book  idref="N1">Шредер К.</author_book>
    </author_catalog>
  </library>
